name: assets_generator_by_zpdl
description: Flutter assets code generator. Read assets in pubsepec.yaml and generates code.
version: 1.1.3
homepage: https://github.com/zpdL-Studio/flutter_boilerplate_by_zpdl

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  yaml: ^3.1.1
  build: ^2.3.1
  source_gen: ^1.2.3
  assets_annotation_by_zpdl: ^1.1.3

dev_dependencies:
  flutter_lints: ^2.0.1

